---
- hosts: localhost
  gather_facts: no
  
  tasks:
    - name: "install apt pkg"
      ansible.builtin.apt:
        pkg:
        - build-essential
        - curl
        - vim
        - fonts-powerline
        - tmux
        - screen
        - htop
        - dos2unix
        - whois
        - nmap
        - jq
        - peek
        - vlc
        - ansible
        - fonts-inconsolata
        - gnupg2
        - ffmpegthumbnailer
        - gstreamer1.0-libav
      become: yes
      become_user: root
    - name: "apt autoclean"
      apt:
        autoclean: yes
      become: yes
      become_user: root
    - name: "apt autoremove"
      apt:
        autoremove: yes
      become: yes
      become_user: root