---
- hosts: localhost
  gather_facts: no
  
  tasks:
    - name: "install apt pkg"
      ansible.builtin.apt:
        pkg:
        - build-essential
        - curl
        - vim
        - fonts-powerline
        - tmux
        - screen
        - htop
        - dos2unix
        - whois
        - nmap
        - jq
        - peek
        - vlc
        - fonts-inconsolata
      become: yes
      become_user: root