---
- hosts: localhost
  gather_facts: no
  
  tasks:
    - name: "instala python3-pip"
      apt:
        name: python3-pip
        state: present
      become: yes
      become_user: root
    - name: "instala ruby"
      apt:
        name: ruby-full
        state: present
      become: yes
      become_user: root