---
- hosts: kafka
  gather_facts: false

  tasks:
  - name: "inicia zookeeper.service"
    systemd:
      name: zookeeper
      state: started
    become: yes
  - name: "inicia kafka.service"
    systemd:
      name: kafka
      state: started
    become: yes