---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    lab:
      hosts:
        base
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: ssh