---
  - name: "script: kafka-server-start.sh"
    copy:
      content: |
        #!/bin/bash
        # kafka-server-start.sh
        # 
        if [ $# -lt 1 ];
        then
                echo "USAGE: $0 [-daemon] server.properties [--override property=value]*"
                exit 1
        fi
        base_dir="/var/opt/kafka/bin"
        if [ "x$KAFKA_LOG4J_OPTS" = "x" ]; then
            export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:$base_dir/../config/log4j.properties"
        fi
        if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
            export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
        fi
        EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer -loggc'}
        COMMAND=$1
        case $COMMAND in
          -daemon)
            EXTRA_ARGS="-daemon "$EXTRA_ARGS
            shift
            ;;
          *)
            ;;
        esac
        exec $base_dir/kafka-run-class.sh $EXTRA_ARGS kafka.Kafka "$@"
      dest: /usr/local/bin/kafka-server-start.sh
      mode: '0755'
    become: yes
  - name: "script: kafka-server-stop.sh"
    copy:
      content: |
        #!/bin/bash
        # kafka-server-stop.sh
        #
         
        SIGNAL=${SIGNAL:-TERM}
        
        OSNAME=$(uname -s)
        if [[ "$OSNAME" == "OS/390" ]]; then
            if [ -z $JOBNAME ]; then
                JOBNAME="KAFKSTRT"
            fi
            PIDS=$(ps -A -o pid,jobname,comm | grep -i $JOBNAME | grep java | grep -v grep | awk '{print $1}')
        elif [[ "$OSNAME" == "OS400" ]]; then
            PIDS=$(ps -Af | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $2}')
        else
            PIDS=$(ps ax | grep ' kafka\.Kafka ' | grep java | grep -v grep | awk '{print $1}')
        fi
        
        if [ -z "$PIDS" ]; then
          echo "No kafka server to stop"
          exit 1
        else
          kill -s $SIGNAL $PIDS
        fi
      dest: /usr/local/bin/kafka-server-stop.sh
      mode: '0755'
    become: yes
  - name: "script: zookeeper-server-start.sh"
    copy:
      content: |
        #!/bin/bash
        # zookeeper-server-start.sh
        # 
        
        if [ $# -lt 1 ];
        then
                echo "USAGE: $0 [-daemon] zookeeper.properties"
                exit 1
        fi
        base_dir="/var/opt/kafka/bin"
        
        if [ "x$KAFKA_LOG4J_OPTS" = "x" ]; then
            export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:$base_dir/../config/log4j.properties"
        fi
        
        if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
            export KAFKA_HEAP_OPTS="-Xmx512M -Xms512M"
        fi
        
        EXTRA_ARGS=${EXTRA_ARGS-'-name zookeeper -loggc'}
        
        COMMAND=$1
        case $COMMAND in
          -daemon)
             EXTRA_ARGS="-daemon "$EXTRA_ARGS
             shift
             ;;
         *)
             ;;
        esac
         
        exec $base_dir/kafka-run-class.sh $EXTRA_ARGS org.apache.zookeeper.server.quorum.QuorumPeerMain "$@"
      dest: /usr/local/bin/zookeeper-server-start.sh
      mode: '0755'
    become: yes
  - name: "script: zookeeper-server-stop.sh"
    copy:
      content: |
        #!/bin/bash
        # zookeeper-server-stop.sh
        #
        
        SIGNAL=${SIGNAL:-TERM}
        
        OSNAME=$(uname -s)
        if [[ "$OSNAME" == "OS/390" ]]; then
            if [ -z $JOBNAME ]; then
                JOBNAME="ZKEESTRT"
            fi
            PIDS=$(ps -A -o pid,jobname,comm | grep -i $JOBNAME | grep java | grep -v grep | awk '{print $1}')
        elif [[ "$OSNAME" == "OS400" ]]; then
            PIDS=$(ps -Af | grep java | grep -i QuorumPeerMain | grep -v grep | awk '{print $2}')
        else
            PIDS=$(ps ax | grep java | grep -i QuorumPeerMain | grep -v grep | awk '{print $1}')
        fi
        
        if [ -z "$PIDS" ]; then
          echo "No zookeeper server to stop"
          exit 1
        else
          kill -s $SIGNAL $PIDS
        fi
      dest: /usr/local/bin/zookeeper-server-stop.sh
      mode: '0755'
    become: yes
...